"""empty message

Revision ID: 370b9a7ad002
Revises: 74fa591f6cfc
Create Date: 2026-04-13 21:41:21.829878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370b9a7ad002'
down_revision = '74fa591f6cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('matchID', sa.Integer(), nullable=False),
    sa.Column('lost_report_id', sa.Integer(), nullable=False),
    sa.Column('found_report_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['found_report_id'], ['found_item_report.reportID'], ),
    sa.ForeignKeyConstraint(['lost_report_id'], ['lost_item_report.reportID'], ),
    sa.PrimaryKeyConstraint('matchID')
    )
    with op.batch_alter_table('found_item_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adminID', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('office_directions', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'User', ['adminID'], ['userID'])
        batch_op.drop_column('office_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('found_item_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('office_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('office_directions')
        batch_op.drop_column('adminID')

    op.drop_table('match')
    # ### end Alembic commands ###
