"""add notification table

Revision ID: 5108237c57ce
Revises: 370b9a7ad002
Create Date: 2026-04-24 18:43:12.258991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5108237c57ce'
down_revision = '370b9a7ad002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.matchID'], ),
    sa.ForeignKeyConstraint(['userID'], ['User.userID'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    with op.batch_alter_table('found_item_report', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('office_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('adminID',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('lost_item_report', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('userID',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_item_report', schema=None) as batch_op:
        batch_op.alter_column('userID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('found_item_report', schema=None) as batch_op:
        batch_op.alter_column('adminID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('office_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    op.drop_table('notification')
    # ### end Alembic commands ###
