"""update user model roles and constraints

Revision ID: 737456191af1
Revises: d6515c69ff01
Create Date: 2026-04-12 21:20:37.728541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '737456191af1'
down_revision = 'd6515c69ff01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.drop_column('lock_until')
        batch_op.drop_column('failed_attempted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_attempted', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lock_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
