"""empty message

Revision ID: 74fa591f6cfc
Revises: 737456191af1
Create Date: 2026-04-13 01:35:30.275711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fa591f6cfc'
down_revision = '737456191af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('found_item_description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_embedding', sa.PickleType(), nullable=True))
        batch_op.drop_column('brand')
        batch_op.drop_column('color')

    with op.batch_alter_table('found_item_report', schema=None) as batch_op:
        batch_op.drop_column('location_found')

    with op.batch_alter_table('lost_item_description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_embedding', sa.PickleType(), nullable=True))
        batch_op.drop_column('brand')
        batch_op.drop_column('color')

    with op.batch_alter_table('lost_item_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'User', ['userID'], ['userID'])
        batch_op.drop_column('location_lost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_item_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_lost', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('userID')

    with op.batch_alter_table('lost_item_description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('image_embedding')

    with op.batch_alter_table('found_item_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_found', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('found_item_description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('image_embedding')

    # ### end Alembic commands ###
