"""empty message

Revision ID: 796dd7b16e0d
Revises: 5108237c57ce
Create Date: 2026-05-05 22:44:28.850931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796dd7b16e0d'
down_revision = '5108237c57ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_status'))

    # ### end Alembic commands ###
