"""Add photo_url to descriptions

Revision ID: d6515c69ff01
Revises: e96765e21ec3
Create Date: 2026-04-12 20:30:39.996117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6515c69ff01'
down_revision = 'e96765e21ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('found_item_description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('lost_item_description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_item_description', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('found_item_description', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
