"""Initial migration

Revision ID: e96765e21ec3
Revises: 
Create Date: 2026-04-05 18:51:17.331116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96765e21ec3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=80), nullable=True),
    sa.Column('lastName', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('failed_attempted', sa.Integer(), nullable=True),
    sa.Column('lock_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('userID')
    )
    op.create_table('found_item_report',
    sa.Column('reportID', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('date_found', sa.DateTime(), nullable=True),
    sa.Column('location_found', sa.String(length=100), nullable=True),
    sa.Column('office_name', sa.String(length=100), nullable=True),
    sa.Column('office_location', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('reportID')
    )
    op.create_table('lost_item_report',
    sa.Column('reportID', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('date_lost', sa.DateTime(), nullable=True),
    sa.Column('location_lost', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('reportID')
    )
    op.create_table('found_item_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('text_description', sa.Text(), nullable=True),
    sa.Column('text_embedding', sa.PickleType(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['found_item_report.reportID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lost_item_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('text_description', sa.Text(), nullable=True),
    sa.Column('text_embedding', sa.PickleType(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['lost_item_report.reportID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lost_item_description')
    op.drop_table('found_item_description')
    op.drop_table('lost_item_report')
    op.drop_table('found_item_report')
    op.drop_table('User')
    # ### end Alembic commands ###
